cc_library(
    name = "gpio_device_mocks",
    srcs = glob(["gpio.h"]),
    hdrs = glob(["gpio.h"]),
    visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "gpio_pins_mocks",
    srcs = glob([
        "pwm.h",
	"output.h",
    ]),
    hdrs = glob([
        "pwm.h",
	"output.h",
	"sensor.h",
	"input.h"
    ]),
    visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "robot_motion_mocks",
    srcs = glob([
        "motor.h",
	"state.h",
    ]),
    hdrs = glob([
        "motor.h",
	"state.h",
    ]),
    visibility = [
        "//visibility:public",
    ],
)
