#cc_test (
#    name = "motor_test",
#    srcs = [
#        "motor_test.cc",
#    ],
#    deps = [
#    	"//modules/control:all",
#        "@gtest//:gtest",
#        "@gtest//:gtest_main",
#    ],
#)

cc_test (
    name = "actuator_test",
    srcs = ["actuators_test.cc"],
    deps = [
        "//modules/control:actuators",
        "@gtest//:gtest",
        "@gtest//:gtest_main"
    ],
)