#cc_test (
#    name = "motor_test",
#    srcs = [
#        "motor_test.cc",
#    ],
#    deps = [
#    	"//modules/control:all",
#        "@gtest//:gtest",
#        "@gtest//:gtest_main",
#    ],
#)

cc_test (
    name = "unicycle_actuator_test",
    srcs = [
        "unicycle_driver_test.cc",
    ],
    deps = [
        "//tareeq/control:unicycle_actuator",
        "@gtest//:gtest",
        "@gtest//:gtest_main"
    ],
)